/* --------------------------------------------------------------------------------------------- 
File:   App.java
Desc.   This class is auto-generated by Node.js and initializes the program.
--------------------------------------------------------------------------------------------- */


import javafx.application.Application;

public class App {  
    public static void main(String[] args) {
        Application.launch(AppGUI.class, args);
    }
}