/* --------------------------------------------------------------------------------------------- 
File:   App.java
Desc.   This class is auto-generated by Node.js and initializes the program.
--------------------------------------------------------------------------------------------- */


import javafx.application.Application;

/**
 * This method is the main launch method for the game application.
 */
public class App {  
    public static void main(String[] args) {
        Application.launch(AppGUI.class, args);
    }
}