/* --------------------------------------------------------------------------------------------- 
File:   AppGUI.java
Desc.   AppGUI is a modified class that is auto-generated by Node.js
        It holds static utility methods for the other FXML.java classes.
Primary Author: Jeremiah Cox 
--------------------------------------------------------------------------------------------- */


import java.io.IOException;
import Game_model.Game.StateDifficulty;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Rectangle2D;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Screen;
import javafx.stage.Stage;


public class AppGUI extends Application {

    
    //  --------------- //
    //    Variables     //
    // ---------------  //


    private static Stage currentStage; // Contains the current GUI stage.
    private static Stage popupStage = new Stage(); // Contains the popup stage


    //  --------------- //
    //     Methods      //
    // ---------------  //


    /**
     * This method takes a stage parameter and launches the title screen.
     */
    @Override
    public void start(Stage stage) throws Exception 
    {
        AppGUI.currentStage = stage;
        AppGUI.windowLoad(this, "Title Screen", "W_TitleScreen.fxml", null);
        currentStage.show();
    }

    /**
     * This method takes the parameters listed below and is used to load popup windows such as the 
     * Level Completed Screen or the Game Over screen.
     * @param parentClass
     * @param windowURL
     * @param windowTitle
     * @throws IOException
     */
    public static void popupLoad(Object parentClass, String windowURL, String windowTitle) throws IOException 
    {        
        FXMLLoader loader = new FXMLLoader(parentClass.getClass().getResource(windowURL));
        Scene scene = new Scene(loader.load());
        AppInitialize ctrl = (AppInitialize)loader.getController();
        ctrl.initialize();
        
        AppGUI.getPopupStage().setScene(scene);
        AppGUI.getPopupStage().setTitle(windowTitle);
        AppGUI.getPopupStage().show();
    }


    /**
     * This method takes parameters for parentClass, new window title, the exact URL of the new window,
     * as well as an object array containing any information needed to load that window (e.g: game level, difficulty, etc).
     * This method can be called by any other VIEW class to load a new window.
     */
    public static void windowLoad(Object parentClass, String newWindowTitle, String windowURL, Object[] windowInitData) 
        throws IOException, InterruptedException 
        {
        currentStage.close();
        currentStage = new Stage();

        var loader = new FXMLLoader(parentClass.getClass().getResource(windowURL));
        var scene = new Scene(loader.load());


        // Change stage properties

        Screen screen = Screen.getPrimary();
        Rectangle2D bounds = screen.getVisualBounds();

        currentStage.setScene(scene);
        currentStage.setTitle(newWindowTitle);
        currentStage.setX(bounds.getMinX());
        currentStage.setY(bounds.getMinY());
        currentStage.setWidth(1340);
        currentStage.setHeight(800);
        currentStage.getIcons().add(new Image("/icons/terminatorIcon2.png"));

        if(newWindowTitle.equals("Game"))
        {               
            W_InGame gameScene = loader.getController();
            gameScene.ingameScene = scene;
            gameScene.initialize((StateDifficulty)windowInitData[0], (int)windowInitData[1], (int) windowInitData[2]);
        }
        else if(newWindowTitle.equals("Main Menu"))
        {
            AppInitialize ctrl = (AppInitialize)loader.getController();
            ctrl.initialize();
        }

        currentStage.show();
    }


    //  --------------- //
    //   Get-Setters    //
    // ---------------  //


    public static void setStage(Stage newStage) {
        currentStage = newStage;
    }

    public static Stage getStage() {
        return currentStage;
    }

    public static Stage getPopupStage() {
        return popupStage;
    }

    public static void setPopupStage(Stage popupStage) {
        AppGUI.popupStage = popupStage;
    }
}
