/* --------------------------------------------------------------------------------------------- 
File:   AppGUI.java
Desc.   AppGUI is a modified class that is auto-generated by Node.js
        It holds static utility methods for the other FXML.java classes.
--------------------------------------------------------------------------------------------- */


import java.io.IOException;
import Game_model.Game.StateDifficulty;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Rectangle2D;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Screen;
import javafx.stage.Stage;


public class AppGUI extends Application {

    
    //  --------------- //
    //    Variables     //
    // ---------------  //


    private static Stage currentStage;
    private static Stage popupStage = new Stage();


    //  --------------- //
    //     Methods      //
    // ---------------  //


    @Override
    public void start(Stage stage) throws Exception 
    {
        AppGUI.currentStage = stage;
        AppGUI.windowLoad(this, "Title Screen", "W_TitleScreen.fxml", null);
        currentStage.show();
    }

    public static void popupLoad(Object parentClass, String windowURL, String windowTitle) throws IOException 
    {        
        FXMLLoader loader = new FXMLLoader(parentClass.getClass().getResource(windowURL));
        Scene scene = new Scene(loader.load());
        AppInitialize ctrl = (AppInitialize)loader.getController();
        ctrl.initialize();
        
        AppGUI.getPopupStage().setScene(scene);
        AppGUI.getPopupStage().setTitle(windowTitle);
        AppGUI.getPopupStage().show();
    }

    public static void windowLoad(Object parentClass, String newWindowTitle, String windowURL, Object[] windowInitData) 
        throws IOException, InterruptedException 
        {
        currentStage.close();
        currentStage = new Stage();

        var loader = new FXMLLoader(parentClass.getClass().getResource(windowURL));
        var scene = new Scene(loader.load());


        // Change stage properties

        Screen screen = Screen.getPrimary();
        Rectangle2D bounds = screen.getVisualBounds();

        currentStage.setScene(scene);
        currentStage.setTitle(newWindowTitle);
        currentStage.setX(bounds.getMinX());
        currentStage.setY(bounds.getMinY());
        currentStage.setWidth(1340);
        currentStage.setHeight(800);
        currentStage.getIcons().add(new Image("/icons/terminatorIcon2.png"));

        if(newWindowTitle.equals("Game"))
        {               
            W_InGame gameScene = loader.getController();
            gameScene.ingameScene = scene;
            gameScene.initialize((StateDifficulty)windowInitData[0], (int)windowInitData[1], (int) windowInitData[2]);
        }
        else if(newWindowTitle.equals("Main Menu"))
        {
            AppInitialize ctrl = (AppInitialize)loader.getController();
            ctrl.initialize();
        }

        currentStage.show();
    }


    //  --------------- //
    //   Get-Setters    //
    // ---------------  //


    public static void setStage(Stage newStage) {
        currentStage = newStage;
    }

    public static Stage getStage() {
        return currentStage;
    }

    public static Stage getPopupStage() {
        return popupStage;
    }

    public static void setPopupStage(Stage popupStage) {
        AppGUI.popupStage = popupStage;
    }
}
